# spring:
#   datasource:
#     driverClassName: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/simplescript?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
#     username: root
#     password:
#     hikari:
#       connectionTimeout: 30000 
#       idleTimeout: 600000 
#       maxLifetime: 1800000
#       maximumPoolSize: 200
  
javafx:
  title: Application Koperasi AHP 2023
  stage:
    resizable: true
  main:
    tree: true

config:
  key: MjAyMy0xMi0wMQ==
  value: QWRla0tyaXN0aXlhbnRvQmFtYmFuZ0Rhbmk=
  fin: ZmFsc2VNakF5TXkweE1pMHdNUT09UVdSbGEwdHlhWE4wYVhsaGJuUnZRbUZ0WW1GdVowUmhibWs9
  app: QXBwbGljYXRpb24tS29wZXJhc2ktQUhQLTIwMjM=MjAyMy0xMi0wMQ==false